### PR TITLE
Generate Version Automatically

### PR DESCRIPTION
**Pull request by fewensa**
Related: https://github.com/darwinia-network/darwinia/pull/866

### CODE REVIEW

**Comment by fewensa** [comment]
```
CVERSION="Crab Parachain-4 (Darwinia Crab Parachain-1.tx1.au1)"
echo $CVERSION | sed 's/.*-\([0-9]*\)[ ].*/\1/g'

4
```

**Review by acgxv — APPROVED** [review]

**Comment by acgxv** [comment]
> `## [{{ tag }}] - 2022-02-16`

What do you think about removing this date?

**Comment by hackfisher** [comment]
> > `## [{{ tag }}] - 2022-02-16`
> 
> 
> 
> What do you think about removing this date?

Sounds good to me, git release tag provides date info.

**Comment by fewensa** [comment]
Yes, we can remove it. If it's required. also set an environment is better
like this

```
date "+%Y-%m-%d"
2022-04-25
```

**Comment by acgxv** [comment]
> Yes, we can remove it. If it's required. also set an environment is better like this
> 
> ```
> date "+%Y-%m-%d"
> 2022-04-25
> ```

Github release contains a date. So I think this is unnecessary.

**Comment by hackfisher** [comment]
OK， let's remove it then, no need for the env for now IMO

**Pull request merged**
